// Bundles the 3D report renderer into public/report/app.js and writes the HTML shell
// into src/lib/report-template.generated.ts. Runs before `next dev` and `next build`.
import { build } from 'esbuild';
import { createHash } from 'crypto';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const r = await build({ entryPoints: [path.join(root, 'renderer/src/main.js')], bundle: true, format: 'iife', minify: true, target: 'es2019', write: false, legalComments: 'none' });
const js = r.outputFiles[0].text;
fs.mkdirSync(path.join(root, 'public/report'), { recursive: true });
fs.writeFileSync(path.join(root, 'public/report/app.js'), js);
const version = createHash('sha256').update(js).digest('hex').slice(0, 10);
const html = fs.readFileSync(path.join(root, 'renderer/template.html'), 'utf8');
fs.writeFileSync(path.join(root, 'src/lib/report-template.generated.ts'),
  `// Generated by renderer/build.mjs. Do not edit; edit renderer/template.html instead.\nexport const REPORT_VERSION = ${JSON.stringify(version)};\nexport const REPORT_TEMPLATE = ${JSON.stringify(html)};\n`);
console.log(`report renderer: ${(js.length / 1024).toFixed(0)} KB, version ${version}`);
